backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Página Inicio"
    files:
      - file: "index.html"
        label: "Inicio"
        name: "inicio"
        fields:
          - { label: "Título principal", name: "title", widget: "string" }
          - { label: "Texto", name: "description", widget: "text" }
          - { label: "Imagen", name: "image", widget: "image" }
